apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest   # Use your ECR image
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123"  # Change this to a secure password
        ports:
        - containerPort: 3306
